let brands = [
  "Adidas",
  "Adidas Originals",
  "Arena",
  "Asics",
  "Asics Tiger",
  "Balenciaga",
  "Billabong",
  "Bottega Veneta",
  "Calvin Klein",
  "Chanel",
  "Chupps",
  "Columbia",
  "Coega",
  "Converse",
  "Ea7 Emporio Armani",
  "Ekn Footwear",
  "Ellesse",
  "Everlast",
  "Fila",
  "Giant",
  "Giorgio Armani",
  "Givenchy",
  "Good News",
  "Havaianas",
  "Hoka",
  "Jordan",
  "Loro Piana",
  "Louis Vuitton",
  "Mango",
  "New Balance",
  "Nike",
  "Nike Golf",
  "Puma",
  "Prada",
  "Reebok",
  "Saint Laurent",
  "Snitch",
  "Speedo",
  "SuperDry",
  "The North Face",
  "Timberland",
  "Tommy Hilfiger",
  "Under Armour",
  "Valentino",
  "Vans",
  "Veja",
  "Venum",
];
export default brands;
